/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package org.thema.mupcity.rule;

import java.awt.BorderLayout;
import java.awt.Frame;
import java.util.Arrays;
import java.util.Collection;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import org.thema.mupcity.Project;
import org.thema.common.param.DefaultParamEditor;
import org.thema.common.param.ParamEditor;

/**
 *
 * @author gvuidel
 */
public class RuleParamDialog extends javax.swing.JDialog {

    ParamEditor<Rule> currentEditor;
    
    public RuleParamDialog(java.awt.Frame parent, Collection<Rule> rules) {
        super(parent, true);
        initComponents();
        setLocationRelativeTo(parent);
        
        ruleList.setModel(new DefaultComboBoxModel(rules.toArray()));
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelButton = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        ruleList = new javax.swing.JList();
        paramPanel = new javax.swing.JPanel();
        distButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rule parameter");

        cancelButton.setText("Close");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setResizeWeight(0.5);

        ruleList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ruleList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ruleListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ruleList);

        jSplitPane1.setLeftComponent(jScrollPane1);

        paramPanel.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setRightComponent(paramPanel);

        distButton.setText("Distances...");
        distButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(distButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(cancelButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cancelButton)
                    .add(distButton))
                .add(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void ruleListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ruleListValueChanged
        if(currentEditor != null)
            currentEditor.validateParam();
        
        paramPanel.removeAll();
        if(ruleList.getSelectedIndex() < 0)     
            return;
        
        Rule rule = (Rule) ruleList.getSelectedValue();
        if(rule.isUsable()) {
            currentEditor = new DefaultParamEditor<Rule>(rule);
            paramPanel.add(currentEditor, BorderLayout.CENTER);
        } else {
            paramPanel.add(new JTextArea("This rule is not enabled.\nIt needs layers : \n" + Arrays.deepToString(rule.getUsedLayers().toArray())), BorderLayout.CENTER);
        }
        pack();
    }//GEN-LAST:event_ruleListValueChanged

    private void distButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distButtonActionPerformed
        new DistanceDialog((Frame)getParent(), Project.getProject()).setVisible(true);
    }//GEN-LAST:event_distButtonActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton distButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel paramPanel;
    private javax.swing.JList ruleList;
    // End of variables declaration//GEN-END:variables

}
